
instance of MSFT_SomFilter
{
	Author = "T0M-hsanchez@harden.ad";
	ChangeDate = "20231214135801.971000-000";
	CreationDate = "20231213093258.545000-000";
	Description = "Microsoft LAPS LEGACY";
	Domain = "harden.ad";
	ID = "{AB2ED8B2-F74B-451E-A90D-C4B2E0446E41}";
	Name = "Legacy-LAPS-Deployment-x32";
	Rules = {
instance of MSFT_Rule
{
	Query = "SELECT * FROM Win32_OperatingSystem WHERE ((not Version like '10.0.2%' and not Version like '10.0.19045%' and not Version like '10.0.19044%' and ProductType = '1') or (not Version like '10.0.2%' and not Version like '10.0.17%' and ProductType = '3')) and OSArchitecture LIKE '%32%'";
	QueryLanguage = "WQL";
	TargetNameSpace = "root\\CIMv2";
}};
};
