
instance of MSFT_SomFilter
{
	Author = "T0M-hsanchez@harden.ad";
	ChangeDate = "20231214135801.971000-000";
	CreationDate = "20231213093258.545000-000";
	Description = "Microsoft LAPS LEGACY";
	Domain = "harden.ad";
	ID = "{2392CB6F-3C27-4913-82CC-71FD4FBF6341}";
	Name = "Legacy-LAPS-Deployment-x64";
	Rules = {
instance of MSFT_Rule
{
	Query = "SELECT * FROM Win32_OperatingSystem WHERE ((not Version like '10.0.2%' and not Version like '10.0.19045%' and not Version like '10.0.19044%' and ProductType = '1') or (not Version like '10.0.2%' and not Version like '10.0.17%' and ProductType = '3')) and (OSArchitecture LIKE '64-bit' or OSArchitecture LIKE '64 bits')";
	QueryLanguage = "WQL";
	TargetNameSpace = "root\\CIMv2";
}};
};
