
instance of MSFT_SomFilter
{
	Author = "T0M-hsanchez@harden.ad";
	ChangeDate = "20231214135801.971000-000";
	CreationDate = "20231213093258.545000-000";
	Description = "Windows LAPS";
	Domain = "harden.ad";
	ID = "{9AF73875-5C0C-46C0-86DC-C421AFC8A82E}";
	Name = "Windows-Laps-Supported";
	Rules = {
instance of MSFT_Rule
{
	Query = "SELECT * FROM Win32_OperatingSystem WHERE ((Version like '10.0.2%' or Version like '10.0.19045%' or Version like '10.0.19044%') and ProductType = '1') or ((Version like '10.0.2%' or Version like '10.0.17%') and ProductType = '3')";
	QueryLanguage = "WQL";
	TargetNameSpace = "root\\CIMv2";
}};
};
