instance of MSFT_SomFilter
{
	Author = "dev@harden.ad";
	ChangeDate = "20230822120000.000000-000";
    CreationDate = "20230822120000.000000-000";
    Description = "Domain Controllers with PDC Emulator Role";
	Domain = "harden.ad";
	ID = "{f8955a6f-40f9-4074-86f9-2dd616b59a6b}";
	Name = "Windows-PDC";
	Rules = {
        instance of MSFT_Rule
        {
            Query = "SELECT * FROM Win32_ComputerSystem WHERE DomainRole = 5";
            QueryLanguage = "WQL";
            TargetNameSpace = "root\\CIMv2";
        }
    };
};